### ISSUE TITLE
Please add Loadium Postman to Jmeter Converter

### ISSUE THREAD

**Issue by Ajay-056** [QAInsights/PerfDemo#1]
Recently I found this useful converter which will save most of the time but there is a catch creating an account is a pre-requisite and this wont work 100%.

Still we may need to do some enhancements. The point here is it will save the time for scripting.

Here is the URL for the converter: https://loadium.com/postman-to-jmeter-converter/

**Comment by QAInsights** [comment]
Thanks @Ajay-056 It has been added.
